app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
logout:
    path: /logout

sitemap:
    path:     /sitemap.xml
    defaults: { _controller: AppBundle:Config:sitemap, _format: xml }

search:
    path:     /search
    defaults: { _controller: AppBundle:Config:search }
