app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
logout:
    path: /logout

sitemap:
    path:     /sitemap.xml
    defaults: { _controller: AppBundle:Default:sitemap, _format: xml }